### ISSUE TITLE
Cronet ObjC Test Bazel Migration

### ISSUE THREAD

**Issue by dennycd** [grpc/grpc-ios#104]
Add bazel target support for [CronetFramework](https://github.com/grpc/grpc/blob/master/src/objective-c/CronetFramework.podspec)  which currently only available as a podspec. This helps unblocks migration of a number of downstream Cocoapod-based tests & app targets that requires Cronet library 

* [CronetTests](https://github.com/grpc/grpc/blob/e2b772cbd8a134b5964a5bdb5f2c41628048f010/src/objective-c/tests/Podfile#L45) 
* [PerfTests](https://github.com/grpc/grpc/blob/e2b772cbd8a134b5964a5bdb5f2c41628048f010/src/objective-c/tests/Podfile#L54)

**Comment by jtattermusch** [comment]
is this done?  https://github.com/grpc/grpc/pull/30439 has been merged.
