### ISSUE TITLE
Cpp test authorization_policy_provider_test_on_ios. StaticDataCreateReturnsProvider test crash 

### ISSUE THREAD

**Issue by dennycd** [grpc/grpc-ios#43]
Sample 
* https://source.cloud.google.com/results/invocations/6a805d1a-ec38-4ae5-af4b-2772d910966a/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_bazel_cpp_ios_tests/log

**Comment by ashithasantosh** [comment]
I ran `authorization_policy_provider_test` locally on mac OS, and it passed for me.
This makes me feel like the issue here could be an ios problem, and not related to the code. Also the test seems to be running successfully for other platforms.

**Comment by dennycd** [comment]
already fixed
