### ISSUE TITLE
Bazel migration for ObjC Unit Test Suite

### ISSUE THREAD

**Issue by dennycd** [grpc/grpc-ios#74]
Migrate existing gRPC ObjC unit test suite to bazel-based test 

*  <https://github.com/grpc/grpc/tree/master/src/objective-c/tests/UnitTests> 

### Current Test Setup 

Current test utilize a [Cocoapod project target](https://github.com/grpc/grpc/blob/2badafbc4d246d5165546a61eeb36aa017987d30/src/objective-c/tests/Podfile#L35) for unit test, and integrated with kokoro CI via script 

* <https://github.com/grpc/grpc/blob/master/src/objective-c/tests/run_one_test.sh> 

The script involves two major stage: pod installation and xcodebuild test run. 

Its corresponding kokoro test components at 

* <https://github.com/grpc/grpc/blob/1cd6e69347cbf62a012477fe184ee6fa8f25d32c/tools/run_tests/run_tests.py#L1069-L1074> 

### New Setup 

We will define new [ios_unit_test](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_unit_test) target for Unit Test and may utilize the following script for bazel integration w/ kokoro 

* <https://github.com/grpc/grpc/blob/master/src/objective-c/tests/run_one_test_bazel.sh>

----

Also we should enable GRPC_VERBOSITY=debug  environment variable when running these tests

---
cc @jtattermusch

**Comment by jtattermusch** [comment]
Any progress here? I had trouble building ObjC with bazel on my mac machine, so it would be good to verify what's needed here by trying it out.

**Comment by HannahShiSFB** [comment]
What problem did you meet?

**Comment by jtattermusch** [comment]
I ran (the InteropTests is just one of the targets I tried randomly):
tools/bazel build //src/objective-c/tests:InteropTests

Which gave me:
```
ERROR: /private/var/tmp/_bazel_jtattermusch/4690b3cecd520a08d66e7529f10bff45/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_x86_64'

ERROR: Analysis of target '//src/objective-c/tests:InteropTests' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
```

And I got stuck there. Do you know how I can fix this?

**Comment by jtattermusch** [comment]
Looks like https://github.com/grpc/grpc/pull/29599 basically addresses this (it runs `//src/objective-c/tests:UnitTests` bazel target), but someone familiar with ObjC tests should doublecheck that.
