### ISSUE TITLE
Bazel Migration for gRPC ObjC Interop Test 

### ISSUE THREAD

**Issue by dennycd** [grpc/grpc-ios#75]
Migrate existing Cocoapod based Interop test suite to bazel 

* <https://github.com/grpc/grpc/tree/master/src/objective-c/tests/InteropTests> 

Existing pod test target defined in 

* <https://github.com/grpc/grpc/blob/2badafbc4d246d5165546a61eeb36aa017987d30/src/objective-c/tests/Podfile#L36> 

Its corresponding kokoro run component at 

* <https://github.com/grpc/grpc/blob/1cd6e69347cbf62a012477fe184ee6fa8f25d32c/tools/run_tests/run_tests.py#L1075-L1080> 

Also we should enable GRPC_VERBOSITY=debug  environment variable when running these tests

----

cc @jtattermusch

**Comment by jtattermusch** [comment]
The `//src/objective-c/tests:InteropTests` bazel target already exists (not sure how closely it matches the pod test), but its build seems broken. Once the targets builds & runs reliably, it can be added to the kokoro test jobs being added here: https://github.com/grpc/grpc/pull/29599

**Comment by jtattermusch** [comment]
Looks like the //src/objective-c/tests:InteropTests builds now, but in my few attempts on the CI, I got the impression that it might be flaky. Let's doublecheck it's flakiness level and enable as part of grpc_objc_bazel_test once possible.

**Comment by jtattermusch** [comment]
@dennycd should we close this?
